GET http://localhost:3000

###
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "asset2",
  "symbol": "A1",
  "price": 100
}

###
GET http://localhost:3000/assets


###
GET http://localhost:3000/wallets

###
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet2"
}

###
GET http://localhost:3000/wallets/wallet1/assets

###
GET http://localhost:3000/wallets/wallet2/assets

###
POST http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

{
  "asset_id": "asset2",
  "shares": 10
}

###
POST http://localhost:3000/wallets/wallet1/orders
Content-Type: application/json

{
  "asset_id": "asset1",
  "shares": 5,
  "price": 100,
  "type": "SELL"
}

###
POST http://localhost:3000/wallets/wallet2/orders
Content-Type: application/json

{
  "asset_id": "asset2",
  "shares": 5,
  "price": 100,
  "type": "BUY"
}

###
GET http://localhost:3000/wallets/wallet1/orders

###
POST http://localhost:3000/wallets/wallet1/orders/execute
Content-Type: application/json

{
  "order_id": "6490eeae9a0e7fbce01e1f0f",
  "status": "CLOSED",
  "related_investor_id": "xxxx",
  "broker_transaction_id": "xxxx",
  "negotiated_shares": 5,
  "price": 10
}